services:
  hytale:
    build: .
    container_name: hytale_server
    ports:
      - "5520:5520/udp"
    volumes:
      # Solo montamos para guardar mundos, logs y config.json
      # El Assets.zip que hay en tu PC ya no se usará, se usará el de la imagen
      - ./:/data
    environment:
      - RAM_MAX=4G
    restart: unless-stopped
    stdin_open: true
    tty: true
